#!/bin/bash

# main user interface
# analyze the photos in input directory and classify them by events and
# copy them to the output directory

[ "$1" == '' -o "$2" == '' ] && echo "usage: $0 <input-dir> <output-dir>" && exit;

class=0;

mkdir -p output;

./parse "$1" | sort -k3 -n > "output/data_$$";
./test "output/data_$$" "model/model.xml" > "output/result_$$";
cat "output/result_$$" | while read -r l n t o le; do
	if [ $l -eq 1 ]; then
		class=$(($class + 1));
		mkdir "$2/$class";
	elif [ $class -eq 0 ]; then
		class=1;
		mkdir "$2/$class";
	fi;
	cp "$1/$n" "$2/$class";
done;
