#!/bin/bash

# take a photo directory as argument, output the photo time info to stdout
# output format will be <label> <name> <timestamp>
# label is 2 by default, it can be flagged manually for training purpose

[ "$1" == '' ] && echo "usage: $0 <photo-dir>" && exit;

label=2;

#exiv2 -g Exif.Image.DateTime -Pv $1/* | sed "s/:/\n/g3; s/:/-/g; s/\n/:/g" | while read -r n d t; do echo -n "2" $(basename $n); echo -n " "; date +%s -d"$d $t"; done;

for f in $(ls "$1"); do
	timestamp=$(exiv2 -g Exif.Image.DateTime -Pv "$1/$f" | sed "s/:/\n/g3; s/:/-/g; s/\n/:/g");
	timestamp=$(date +%s -d "$timestamp");
	orientation=$(exiv2 -g Exif.Image.Orientation -Pv "$1/$f");
	lens=$(exiv2 -g Exif.Photo.LensModel -Pv "$1/$f");
	echo $lens | grep -q "front";
	lens=$?;
	echo "$label $f $timestamp $orientation $lens";
done;
