#!/bin/bash

# tune SVM parameters to get optimized result with cross validation
# try 10 C and 10 gamma, result will be saved to output/log

C=0.001;

mkdir -p output;

for i in $(seq 10); do
	gamma=0.00000001;
	for j in $(seq 10); do
		m=$(./validate $C $gamma)
		echo $m >> output/log
		gamma=$(bc <<< "$gamma * 10");
	done;
	C=$(bc <<< "$C * 10");
done;
