#!/bin/bash

# take C and gamma as arguments
# get cross validation result from the training model with the C and gamma

[ "$1" == '' -o "$2" == '' ] && echo "usage: $0 <C> <gamma>" && exit;

err=0;

mkdir -p output;

for i in $(seq 4); do
	./train "data/data_train_$i" "model/model_$i" "$1" "$2";
	./test "data/data_test_$i" "model/model_$i" > "output/result_test_$i";
	e=$(diff -U 0 "data/data_test_$i" "output/result_test_$i" | grep -v ^@ | wc -l);
	e=$((($e - 2) / 2));
	err=$(($err + $e));
done;

echo "$err --- C: $1, gamma: $2";
